SET NAMES utf8mb4;
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL';

DROP SCHEMA IF EXISTS todo;
CREATE SCHEMA todo;
USE todo;

DROP TABLE IF EXISTS TASK;

CREATE TABLE TASK (
  id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  title VARCHAR(50) NOT NULL,
  content VARCHAR(100) NOT NULL,
  priority TINYINT UNSIGNED NOT NULL DEFAULT 3,
  completion BOOLEAN NOT NULL DEFAULT false,
  user_id VARCHAR(10) NOT NULL,
  update_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY  (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;



INSERT INTO TASK VALUES (1,'HTMLを学習する','コーポレートサイトを作成する。',1,false,'aikawa','2006-02-15 04:34:33'),
(2,'CSSを学習する','ハンバーガーメニューを作成する。',2,true,'aikawa','2006-02-15 04:34:33'),
(3,'javaを学習する','MVCとは何かを調査する。',2,true,'aikawa','2006-02-15 04:34:33'),
(4,'Reactを学習する','レンダリングについて確認する。',3,false,'aikawa','2006-02-15 04:34:33');

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;